import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Layout from '../components/Layout'
import Head from 'next/head'
import GlobalContext from '../context/context'
import { useState } from 'react'

function MyApp({ Component, pageProps }: AppProps) {
  const [klaytnProvider, setKlaytnProvider] = useState()
  const [ethProvider, setEthProvider] = useState()
  const [metamaskAddress, setMetamaskAddress] = useState()
  const [web3, setWeb3] = useState()

  const contextData = {
    klaytnProvider: klaytnProvider,
    ethProvider: ethProvider,
    metamaskAddress: metamaskAddress,
    web3: web3,
    setKlaytnProvider: setKlaytnProvider,
    setEthProvider: setEthProvider,
    setMetamaskAddress: setMetamaskAddress,
    setWeb3: setWeb3,
  }

  return (
    <div>
      <GlobalContext.Provider value={contextData}>
        <Head>
          <title>klaytn</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </GlobalContext.Provider>
    </div>
  )
}

export default MyApp
